version: '3.8'

services:
  db:
    image: mariadb:10.9
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: {$TZ}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - zoneminder_network

  zoneminder:
    environment:
      ZM_DB_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ZM_DB_NAME: ${MYSQL_DATABASE}
      ZM_DB_USER: ${MYSQL_USER}
      ZM_DB_PASS: ${MYSQL_PASSWORD}
      ZM_SERVER_HOST: zoneminder
      TZ: {$TZ}
    volumes:
      - zm_config:/etc/zm
      - zm_cache:/var/cache/zoneminder
      - known_faces:/var/lib/zmeventnotification/hooks/known_faces
      - unknown_faces:/var/lib/zmeventnotification/hooks/unknown_faces
      - type: tmpfs 
        target: /dev/shm 
        tmpfs: 
          size: 400000000 #~ 400 MB
    networks:
      - zoneminder_network

volumes:
  db_data:
  zm_config:
  known_faces:
  unknown_faces:

networks:
  zoneminder_network:
