services:
  zoneminder:
    build:
      context: .
      dockerfile: Dockerfile  
    ports: 
      - "7080:80"
      - "7000:9000"
  eclipse-mosquitto:
    build:
      context: .
      dockerfile: Dockerfile.mosquitto
    ports:
      - 1883:1883
      - 9001:9001  
